### ISSUE TITLE
AMQP.basic_publish fails with ValueError: channel must be a valid rabbitpy Channel object

### ISSUE THREAD

**Issue by vitaly-krugl** [gmr/rabbitpy#72]
I followed the example at https://rabbitpy.readthedocs.org/en/latest/api/amqp.html for setting up the less opinionated interface.

This traceback results from executing the code below using the latest rabbitpy from master 75d6b7546bca855bdbf2a9ebd35ad8a8adcd9bf7 as well as from pypi:

```
Traceback (most recent call last):
  File "rabbitpy_perf.py", line 190, in <module>
    main()
  File "rabbitpy_perf.py", line 42, in main
    _handlePublishTest(sys.argv[2:])
  File "rabbitpy_perf.py", line 130, in _handlePublishTest
    deliveryConfirmation=options.deliveryConfirmation)
  File "rabbitpy_perf.py", line 176, in runBlockingPublishTest
    g_log.info("%s: closing connection", implClassName)
  File "rabbitpy_perf.py", line 174, in runBlockingPublishTest
    g_log.info("%s: closing channel", implClassName)
  File "rabbitpy_perf.py", line 169, in runBlockingPublishTest
    body=message)
  File "/Users/vkruglikov/ossdev/rabbitpy/rabbitpy/amqp.py", line 151, in basic_publish
    msg = message.Message(self, body, properties or {}, False, False)
  File "/Users/vkruglikov/ossdev/rabbitpy/rabbitpy/message.py", line 102, in __init__
    super(Message, self).__init__(channel, 'Message')
  File "/Users/vkruglikov/ossdev/rabbitpy/rabbitpy/base.py", line 36, in __init__
    raise ValueError('channel must be a valid rabbitpy Channel object')
ValueError: channel must be a valid rabbitpy Channel object
```

```
# Code from https://github.com/vitaly-krugl/amqp-perf
import logging
import rabbitpy

g_log = logging

ROUTING_KEY = "test"

def runBlockingPublishTest(implClassName,
                           exchange,
                           numMessages,
                           messageSize,
                           deliveryConfirmation):
  g_log.info("runBlockingPublishTest: impl=%s; exchange=%s; numMessages=%d; "
             "messageSize=%s; deliveryConfirmation=%s", implClassName, exchange,
             numMessages, messageSize, deliveryConfirmation)

  implClass = getattr(rabbitpy, implClassName)

  assert implClass is rabbitpy.AMQP, implClass

  with rabbitpy.Connection(getConnectionParameters()) as conn:
    g_log.info("%s: opened connection", implClassName)

    with conn.channel() as channel:
      g_log.info("%s: opened channel", implClassName)

      amqp = rabbitpy.AMQP(channel)
      g_log.info("%s: wrapped channel", implClassName)

      if deliveryConfirmation:
        amqp.confirm_select()
        g_log.info("%s: enabled message delivery confirmation", implClassName)


      # Publish
      message = "a" * messageSize

      for i in xrange(numMessages):
        amqp.basic_publish(exchange=exchange, routing_key=ROUTING_KEY,
                           body=message)
      else:
        g_log.info("Published %d messages of size=%d via=%s",
                   i+1, messageSize, implClass)

      g_log.info("%s: closing channel", implClassName)

    g_log.info("%s: closing connection", implClassName)




def getConnectionParameters():
  """
  :returns: URL string respresenting broker connection parameters
  """
  return "amqp://guest:guest@localhost:5672/%2F"


runBlockingPublishTest('AMQP', exchange='', numMessages=1, messageSize=1024, deliveryConfirmation=True)
```

**Comment by gmr** [comment]
Sorry for the delay in this. I believe this is long fixed, and just ran it with the following results:

```
INFO:root:runBlockingPublishTest: impl=AMQP; exchange=; numMessages=1; messageSize=1024; deliveryConfirmation=True
DEBUG:rabbitpy.base:Connection setting state to 'Opening'
DEBUG:rabbitpy.base:IO setting state to 'Opening'
DEBUG:rabbitpy.events:Waiting for 3 seconds on event: Socket Connected
DEBUG:rabbitpy.io:Connecting to ('::1', 5672, 0, 0)
DEBUG:rabbitpy.io:Error connecting to ('::1', 5672, 0, 0): [Errno 61] Connection refused
DEBUG:rabbitpy.io:Connecting to ('127.0.0.1', 5672)
DEBUG:rabbitpy.base:IO setting state to 'Open'
DEBUG:rabbitpy.connection:Adding channel 0 to io
DEBUG:rabbitpy.io:Socket connected
DEBUG:rabbitpy.base:Channel0 setting state to 'Opening'
DEBUG:rabbitpy.io:Returning PollPoller
DEBUG:rabbitpy.base:Writing frame: ProtocolHeader
DEBUG:rabbitpy.channel0:Received frame: 'Connection.Start'
DEBUG:rabbitpy.channel0:Server b'information': b'Licensed under the MPL.  See http://www.rabbitmq.com/'
DEBUG:rabbitpy.channel0:Server b'cluster_name': b'rabbit@gmr-home.home.poisonpenllc.com'
DEBUG:rabbitpy.channel0:Server b'product': b'RabbitMQ'
DEBUG:rabbitpy.channel0:Server b'version': b'3.6.4'
DEBUG:rabbitpy.channel0:Server b'copyright': b'Copyright (C) 2007-2016 Pivotal Software, Inc.'
DEBUG:rabbitpy.channel0:Server b'platform': b'Erlang/OTP'
DEBUG:rabbitpy.channel0:Server b'capabilities': {b'consumer_cancel_notify': True, b'consumer_priorities': True, b'direct_reply_to': True, b'publisher_confirms': True, b'connection.blocked': True, b'exchange_exchange_bindings': True, b'authentication_failure_close': True, b'per_consumer_qos': True, b'basic.nack': True}
DEBUG:rabbitpy.base:Writing frame: Connection.StartOk
DEBUG:rabbitpy.channel0:Received frame: 'Connection.Tune'
DEBUG:rabbitpy.channel0:Heartbeat interval (server/client): 60/60
DEBUG:rabbitpy.base:Writing frame: Connection.TuneOk
DEBUG:rabbitpy.base:Writing frame: Connection.Open
DEBUG:rabbitpy.channel0:Received frame: 'Connection.OpenOk'
DEBUG:rabbitpy.channel0:Connection opened
DEBUG:rabbitpy.base:Channel0 setting state to 'Open'
DEBUG:rabbitpy.heartbeat:Heartbeat started, ensuring data is written at least every 30.00 seconds
DEBUG:rabbitpy.base:Connection setting state to 'Open'
INFO:root:AMQP: opened connection
DEBUG:rabbitpy.connection:Adding channel 1 to io
DEBUG:rabbitpy.base:Channel setting state to 'Opening'
DEBUG:rabbitpy.base:Writing frame: Channel.Open
DEBUG:rabbitpy.base:Waiting on <class 'pamqp.specification.Channel.OpenOk'> frame(s)
DEBUG:rabbitpy.channel:Checking for RPC request: <pamqp.specification.Channel.OpenOk object at 0x10990e138>
DEBUG:rabbitpy.base:Channel setting state to 'Open'
DEBUG:rabbitpy.channel:Channel #1 open
INFO:root:AMQP: opened channel
INFO:root:AMQP: wrapped channel
DEBUG:rabbitpy.base:Issuing RPC to RabbitMQ: <pamqp.specification.Confirm.Select object at 0x10990e138>
DEBUG:rabbitpy.base:Sending 'Confirm.Select'
DEBUG:rabbitpy.base:Writing frame: Confirm.Select
DEBUG:rabbitpy.base:Waiting on 'Confirm.SelectOk' frame(s)
DEBUG:rabbitpy.channel:Checking for RPC request: <pamqp.specification.Confirm.SelectOk object at 0x109901898>
INFO:root:AMQP: enabled message delivery confirmation
DEBUG:rabbitpy.base:Writing frames: ['Basic.Publish', 'ContentHeader', 'ContentBody']
INFO:root:Published 1 messages of size=1024 via=<class 'rabbitpy.amqp.AMQP'>
INFO:root:AMQP: closing channel
DEBUG:rabbitpy.base:Channel setting state to 'Closing'
DEBUG:rabbitpy.base:Channel 1 close invoked while Closing
DEBUG:rabbitpy.channel:Checking for RPC request: <pamqp.specification.Basic.Ack object at 0x109901ac8>
DEBUG:rabbitpy.base:Read frame while shutting down: <pamqp.specification.Basic.Ack object at 0x109901ac8>
DEBUG:rabbitpy.base:Channel 1 Waiting for a valid response for Channel.Close
DEBUG:rabbitpy.base:Sending 'Channel.Close'
DEBUG:rabbitpy.base:Writing frame: Channel.Close
DEBUG:rabbitpy.base:Waiting on 'Channel.CloseOk' frame(s)
DEBUG:rabbitpy.channel:Checking for RPC request: <pamqp.specification.Channel.CloseOk object at 0x109901ac8>
DEBUG:rabbitpy.base:Channel setting state to 'Closed'
DEBUG:rabbitpy.base:Channel #1 closed
INFO:root:AMQP: closing connection
DEBUG:rabbitpy.base:Connection setting state to 'Closing'
DEBUG:rabbitpy.base:Channel0 setting state to 'Closing'
DEBUG:rabbitpy.base:Sending 'Connection.Close'
DEBUG:rabbitpy.base:Writing frame: Connection.Close
DEBUG:rabbitpy.base:Waiting on 'Connection.CloseOk' frame(s)
DEBUG:rabbitpy.channel0:Received frame: 'Connection.CloseOk'
DEBUG:rabbitpy.base:Channel0 setting state to 'Closed'
DEBUG:rabbitpy.connection:Waiting on socket to close
DEBUG:rabbitpy.events:Waiting for 0 seconds on event: Socket Closed
DEBUG:rabbitpy.io:Exiting due to closing socket
DEBUG:rabbitpy.io:Exiting IOLoop.run
DEBUG:rabbitpy.io:Exiting IO.run
DEBUG:rabbitpy.base:IO setting state to 'Closing'
DEBUG:rabbitpy.base:IO setting state to 'Closed'
DEBUG:rabbitpy.connection:Setting to closed
DEBUG:rabbitpy.base:Connection setting state to 'Closed'
```
