### ISSUE TITLE
Exception during formatting rabbitpy exception string

### ISSUE THREAD

**Issue by kirgene** [gmr/rabbitpy#82]
During handling of rabbitpy exception in try-except block I'm getting following exception:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 980, in emit
    msg = self.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 830, in format
    return fmt.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 567, in format
    record.message = record.getMessage()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 328, in getMessage
    msg = str(self.msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\rabbitpy\exceptions.py", line 43, in __str__
    return 'Unable to connect to the remote server %r' % self.args
TypeError: not all arguments converted during string formatting
```

As a fix, the statement can be written like
```
'Unable to connect to the remote server {0}'.format(self.args)
```
See: https://www.python.org/dev/peps/pep-3101/

**Comment by gmr** [comment]
Thanks, this was addressed in a previous version but I forgot to close the ticket.
